### ISSUE TITLE
Cannot open include file: 'unistd.h': No such file or directory

### ISSUE THREAD

**Issue by coolk8** [adamwestman/extension-vibrate#2]
Hello! Unfortunately, I can' use this addon. Maybe I need to have some framework installed?

1. Start new mobile project in Defold
2. Add https://github.com/adamwestman/extension-vibrate/archive/0.2.0.zip to Dependencies
3.  Project > Fetch dependencies
4.  Vibrate added to project
5. Project > Build 
6. Build errors shows: 
![image](https://user-images.githubusercontent.com/13322564/40414336-998be3d8-5e80-11e8-8aa2-5015fc9f5d92.png)

Platform windows 10

**Comment by subsoap** [comment]
![2018-05-23 17_01_52-lnpoverlaywindow](https://user-images.githubusercontent.com/409170/40457433-4ab95ac6-5eab-11e8-9dd0-d823a7563085.png)

Here is a fix for this, you will need to download the extension as a zip and place it into your project to edit the file.

```
#if defined(DM_PLATFORM_IOS) || defined(DM_PLATFORM_OSX) || defined(DM_PLATFORM_ANDROID)
#include <unistd.h>
#endif
```

**Comment by subsoap** [comment]
Fix was merged this can be closed now.

**Comment by adamwestman** [comment]
Thanks for the help @subsoap !
